apiVersion: apps/v1
kind: Deployment
metadata:
  name: kloudwatcher-prediction-service
spec:
  template:
    spec:
      containers:
      - name: prediction-service
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
            ephemeral-storage: "5Gi"
        env:
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              name: gcp-config
              key: project-id
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-storage-pvc 